### ISSUE TITLE
Stockfish crashes on invalid position instead of error mesasge

### ISSUE THREAD

**Issue by mjg1000** [zhelyabuzhsky/stockfish#97] opened 2022-06-02 10:58 UTC
When stockfish is given a position where both kings are in check, such as 1q2nB2/pP1k2KP/NN1Q1qP1/8/1P1p4/4p1br/3R4/6n1/ w, stockfish will simply crash. Is there a way to instead of crashing throwing an error message, as then it would be possible to use a try: except: statement to filter out these positions?

**Comment by kieferro** [comment] 2022-06-02 19:26
I would also like to have an error message for invalid FENs that can be caught.
I think a change to the `_read_line`-function like this would work:
```python
def _read_line(self) -> str:
    if not self._stockfish.stdout:
        raise BrokenPipeError()
    if self._stockfish.poll() is not None:
        raise AttributeError(
            "Stockfish has crashed. This was probably caused by an invalid FEN."
        )
    return self._stockfish.stdout.readline().strip()
```
What do you think @zhelyabuzhsky? I could add that, some checks with invalid FENs and an entry in the README and then open a PR if you want this feature to be included.

**Comment by johndoknjas** [comment] 2022-06-02 21:08
@kieferro I think that would be good to include. An invalid FEN can cause SF to either crash, or return (none) for the best move (in both cases, after giving it the "go" command). It looks like your code handles the first case. I'm writing some stuff which could help with that, and also detect the second case.

Would u like me to make a PR to your repo? We could work on your branch together and then when done you can make the PR to the official repo here.

**Comment by kieferro** [comment] 2022-06-02 21:58
@johndoknjas Okay, I've already included my code and a unittest on my fork. Feel free to take care of the second case. As long as both cases return the same kind of error, everything should be fine.
Do you want me to make the change to the README as well? I would just add a section and write that when an invalid FEN is entered, a ValueError with the text "Stockfish has crashed. This was probably caused by an invalid FEN." gets raised and maybe explain how to catch it. Does this fit with what you are planning on doing?

**Comment by johndoknjas** [comment] 2022-06-02 23:57
@kieferro I think your error message makes sense, since the process just stopping has a good chance of being caused by a bad FEN. Although in the readme, you could say that it's not guaranteed invalid FENs will cause a crash. The stuff I'm doing more or less tries to deal with these kinds of FENs. So I think what you have fits with my code, and updating the readme is fine. My PR will involve some stuff other than fen validation, so I'll probably wait until yours is merged into master first. As far as error messages go, right now my plan for my function is to just return a bool instead, and then say in the readme that the user can call this function to test their FEN. For your code though, returning an error should be done, since generally if read_line is called, errors aren't the expected behaviour.

**Comment by kieferro** [comment] 2022-06-03 19:41
@johndoknjas Yes, that makes sense. Thank you

**Closed** 2022-06-07 12:08 UTC
