### ISSUE TITLE
can't use stockfish_mv in google colab

### ISSUE THREAD

**Issue by sugizo** [zhelyabuzhsky/stockfish#131] opened 2023-04-22 20:22 UTC
**step on google colab**
!apt-get install -y stockfish curl unzip make git 
!git clone https://github.com/ddugovic/Stockfish
!cd Stockfish/src && make -j build ARCH=x86-64
!cp Stockfish/src/stockfish /bin/stockfish_mv

**result**
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-16-d7ed8b0317d3>](https://localhost:8080/#) in on_change_engine(self, change)
    117         with self.output_board_info:
    118             clear_output(wait = True)
--> 119             display(HTML(self.display_board_info(self.board) ) )
    120 
    121     def make_engine_list(self):

3 frames
[/usr/local/lib/python3.9/dist-packages/stockfish/models.py](https://localhost:8080/#) in __init__(self, path, depth, parameters)
     55         self._has_quit_command_been_sent = False
     56 
---> 57         self._stockfish_major_version: int = int(
     58             self._read_line().split(" ")[1].split(".")[0].replace("-", "")
     59         )

ValueError: invalid literal for int() with base 10: 'dev20230413f0fc36bf'
```

**note**
stockfish_mv from the same git repo run well on mac

best regards

**Comment by kieferro** [comment] 2023-04-22 20:32
Hi, the project is now maintained on [a fork](https://github.com/py-stockfish/stockfish) (for more information please read #130).
The problem you have is a duplicate of https://github.com/py-stockfish/stockfish/issues/11 and we are already working on it. So you can simply close this one. If you open issues in the future, please do so in the new repo.
Thanks

**Closed as completed** 2023-04-23 03:18 UTC
